import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Themeprovider from "@/components/Themeprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "We|Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white dark:bg-dark font-family ${geistSans.variable} ${geistMono.variable} antialiased bg-dark`}
      >
         <Themeprovider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <main>
            {children}
            </main>
        </Themeprovider>
      </body>
    </html>
  );
}
